#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROS_DISTRO="${ROS_DISTRO:-jazzy}"
BAG_PATH="${ROOT_DIR}/bags/ci_synthetic_gs_demo"
FRONTEND_BAG_PATH="${ROOT_DIR}/bags/ci_synthetic_frontend_raw_demo"
ARTIFACT_DIR="${GAUSSIAN_LIC_CI_REPLAY_ARTIFACT_DIR:-/tmp/gaussian_lic_ci_replay_artifacts}"
DURATION_SEC=4
TIMEOUT_SEC=20
PUBLISH_TF=true

usage() {
  cat <<'EOF'
Usage: scripts/ci_replay_smoke.sh [--bag DIR] [--frontend-bag DIR] [--artifact-dir DIR] [--duration SEC] [--timeout SEC] [--no-tf]

Records short synthetic rosbag2 sequences, then replays mapper-contract bags and
raw frontend bags through the ROS2 smoke paths. It also writes bag-contract and
offline artifact-extraction reports.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --bag)
      BAG_PATH="$2"
      shift 2
      ;;
    --frontend-bag)
      FRONTEND_BAG_PATH="$2"
      shift 2
      ;;
    --artifact-dir)
      ARTIFACT_DIR="$2"
      shift 2
      ;;
    --duration)
      DURATION_SEC="$2"
      shift 2
      ;;
    --timeout)
      TIMEOUT_SEC="$2"
      shift 2
      ;;
    --no-tf)
      PUBLISH_TF=false
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

cd "${ROOT_DIR}"
set +u
source "/opt/ros/${ROS_DISTRO}/setup.bash"
source "${ROOT_DIR}/install/setup.bash"
set -u

rm -rf "${ARTIFACT_DIR}"
mkdir -p "${ARTIFACT_DIR}"

smoke_args=(--bag "${BAG_PATH}" --timeout "${TIMEOUT_SEC}")
if [[ "${PUBLISH_TF}" == "true" ]]; then
  smoke_args+=(--tf)
fi

echo "[ci-smoke] recording synthetic bag: ${BAG_PATH}"
./scripts/create_synthetic_bag.sh \
  --output "${BAG_PATH}" \
  --duration "${DURATION_SEC}"

echo "[ci-smoke] recording frontend raw synthetic bag: ${FRONTEND_BAG_PATH}"
./scripts/create_synthetic_bag.sh \
  --frontend-raw \
  --frontend-raw-odometry \
  --output "${FRONTEND_BAG_PATH}" \
  --duration "${DURATION_SEC}"

echo "[ci-smoke] replaying full mapper contract"
./scripts/smoke_test.sh "${smoke_args[@]}"

echo "[ci-smoke] replaying mapper_minimal contract"
./scripts/smoke_test.sh \
  --bag "${BAG_PATH}" \
  --minimal-inputs \
  --timeout "${TIMEOUT_SEC}"

echo "[ci-smoke] replaying frontend raw contract through LIC2 adapter"
frontend_smoke_args=(
  --bag "${FRONTEND_BAG_PATH}"
  --frontend-adapter
  --skip-rendered-data-check
  --timeout "${TIMEOUT_SEC}"
)
if [[ "${PUBLISH_TF}" == "true" ]]; then
  frontend_smoke_args+=(--tf)
fi
./scripts/smoke_test.sh "${frontend_smoke_args[@]}"

echo "[ci-smoke] writing bag contract reports: ${ARTIFACT_DIR}"
ros2 run gaussian_lic_tools gaussian_lic_bag_check \
  --bag "${BAG_PATH}" \
  --json \
  >"${ARTIFACT_DIR}/bag_contract_full.json"
rg -q '"contract_ok": true' "${ARTIFACT_DIR}/bag_contract_full.json"
ros2 run gaussian_lic_tools gaussian_lic_bag_check \
  --bag "${BAG_PATH}" \
  --contract mapper_minimal \
  --json \
  >"${ARTIFACT_DIR}/bag_contract_mapper_minimal.json"
rg -q '"contract_ok": true' "${ARTIFACT_DIR}/bag_contract_mapper_minimal.json"
ros2 run gaussian_lic_tools gaussian_lic_bag_check \
  --bag "${FRONTEND_BAG_PATH}" \
  --contract frontend_raw \
  --json \
  >"${ARTIFACT_DIR}/bag_contract_frontend_raw.json"
rg -q '"contract_ok": true' "${ARTIFACT_DIR}/bag_contract_frontend_raw.json"

echo "[ci-smoke] writing offline artifact extraction reports"
ros2 run gaussian_lic_tools gaussian_lic_offline \
  --bag "${BAG_PATH}" \
  --output "${ARTIFACT_DIR}/offline" \
  >"${ARTIFACT_DIR}/offline_stdout.json"
test -f "${ARTIFACT_DIR}/offline/trajectory.tum"
test -f "${ARTIFACT_DIR}/offline/point_cloud_debug.ply"
test -f "${ARTIFACT_DIR}/offline/metrics.json"
rg -q '"bag_format": "ros2"' "${ARTIFACT_DIR}/offline/metrics.json"
rg -q '"points_with_color": [1-9]' "${ARTIFACT_DIR}/offline/metrics.json"
rg -q " 255 32 16$" "${ARTIFACT_DIR}/offline/point_cloud_debug.ply"

./scripts/replay_artifact_summary.py \
  --artifact-dir "${ARTIFACT_DIR}" \
  --output "${ARTIFACT_DIR}/replay_summary.md"

cat >"${ARTIFACT_DIR}/README.md" <<EOF
# Gaussian-LIC CI Replay Smoke Artifacts

Generated by scripts/ci_replay_smoke.sh.

- bag_contract_full.json
- bag_contract_mapper_minimal.json
- bag_contract_frontend_raw.json
- offline_stdout.json
- offline/metrics.json
- offline/trajectory.tum
- offline/point_cloud_debug.ply
- replay_summary.md
EOF

echo "[ci-smoke] artifacts: ${ARTIFACT_DIR}"
echo "[ci-smoke] passed"
